### ISSUE TITLE
Document if there are any characters that cannot be used in naming the image name

### ISSUE THREAD

**Issue by gioppoluca** [CloudOpting/cloudopting-crane#12]
We need to know if there are any characters not usable so we check in the orchestration process that there are not problems

**Comment by jmcerpa** [comment]
image name must match "[a-z0-9](?:-*[a-z0-9])*(?:[._][a-z0-9](?:-*[a-z0-9])*)*"

**Comment by jmcerpa** [comment]
```
  image name must match "[a-z0-9](?:-*[a-z0-9])*(?:[._][a-z0-9](?:-*[a-z0-9])*)*"
```
