### ISSUE TITLE
we need to know which are the characters not usable in the container name

### ISSUE THREAD

**Issue by gioppoluca** [CloudOpting/cloudopting-crane#13]
Also for the container name as in #12 we need to know the set of allowed characters

**Comment by jmcerpa** [comment]
container name: only [a-zA-Z0-9][a-zA-Z0-9_.-] are allowed

**Comment by gioppoluca** [comment]
Also considering compose etc?

----Messaggio originale----

Da: jmcerpa notifications@github.com

Data: 03/02/2016 16.44

A: "CloudOpting/cloudopting-crane"cloudopting-crane@noreply.github.com

Cc: "Luca Gioppo"gioppoluca@libero.it

Ogg: Re: [cloudopting-crane] we need to know which are the characters not usable in the container name (#13)

container name: only [a-zA-Z0-9][a-zA-Z0-9_.-] are allowed

**Comment by jmcerpa** [comment]
These are the characters. as naming rules are in #16
