### ISSUE TITLE
Execution faliure: No mudule named urllib.parse

### ISSUE THREAD

**Issue by gioppoluca** [CloudOpting/cloudopting-crane#2]
Have this ImportError in the execution
any hints?

**Comment by j-fuentes** [comment]
I tried in a new clean environment. With `pip install -r install/requirements.txt` and `python commander/commander.py` it runs.

I need some more indications to reproduce the error. Could you explain with detail the steps you have followed?.

Which version of python are you using?

**Comment by gioppoluca** [comment]
I have python 2.7.5 on CentOS 7
Followed the instructions in the GIT

**Comment by gioppoluca** [comment]
[root@localhost cloudopting-crane]# python commander/commander.py
Traceback (most recent call last):
  File "commander/commander.py", line 9, in <module>
    from controllers.builder import builderOps
  File "/home/gioppo/git/cloudopting-crane/commander/controllers/builder/builderOps.py", line 9, in <module>
    from toolbox import docker
  File "/home/gioppo/git/cloudopting-crane/commander/toolbox/docker.py", line 26, in <module>
    dockerpy = import_non_local('docker', 'dockerpy')
  File "/home/gioppo/git/cloudopting-crane/commander/toolbox/docker.py", line 20, in import_non_local
    module = imp.load_module(custom_name, f, pathname, desc)
  File "/usr/lib/python2.7/site-packages/docker/**init**.py", line 20, in <module>
    from .client import Client, AutoVersionClient # flake8: noqa
  File "/usr/lib/python2.7/site-packages/docker/client.py", line 37, in <module>
    import websocket
  File "/usr/lib/python2.7/site-packages/websocket/**init**.py", line 22, in <module>
    from ._core import *
  File "/usr/lib/python2.7/site-packages/websocket/_core.py", line 41, in <module>
    from ._url import *
  File "/usr/lib/python2.7/site-packages/websocket/_url.py", line 23, in <module>
    from six.moves.urllib.parse import urlparse
ImportError: No module named urllib.parse

**Comment by gioppoluca** [comment]
Using the home repo not branches

**Comment by j-fuentes** [comment]
I have been recreating all the installation process in a virtual machine with centos7 from scratch.

In the step 'Install pip', I had problems because by default python-pip is not in the yum repositories. I changed the installation method in the readme. Now it is installed with `curl "https://bootstrap.pypa.io/get-pip.py" -o "get-pip.py"` and `python get-pip.py`.

Could you check if you achieved to install pip? With `pip -V` for example.

**Comment by j-fuentes** [comment]
I achieved to run the program just following the steps.

I start from a centos7 x64 clean vagrant box: https://github.com/holms/vagrant-centos7-box/releases/download/7.1.1503.001/CentOS-7.1.1503-x86_64-netboot.box

**Comment by gioppoluca** [comment]
I have pip version 1.5.6.
All installation stated to be correct no errors anywhere

**Comment by j-fuentes** [comment]
I have pip 7.1.0.

Try installing a newer pip version and reinstalling the dependences with `pip install -r install/requirements.txt`

PD: remove pip and install it with `curl "https://bootstrap.pypa.io/get-pip.py" -o "get-pip.py"`  and `python get-pip.py`

**Comment by gioppoluca** [comment]
Fixed with
pip install --upgrade six
Sure it was not needed this dependency?

**Comment by j-fuentes** [comment]
`six` is included by default. It seems that you had an obsolete version or something.

Anyway, I am going to include a note in the readme.

Thanks you. This is good to improve.
