### ISSUE TITLE
build image error

### ISSUE THREAD

**Issue by gioppoluca** [CloudOpting/cloudopting-crane#3]
Here is the error I get
127.0.0.1 - - [10/Jul/2015 16:16:29] "GET /builder/contexts/CTdV02EQ HTTP/1.1" 200 -
127.0.0.1 - - [10/Jul/2015 16:16:29] "POST /builder/images HTTP/1.1" 200 -
Exception in thread Thread-14:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 811, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 764, in run
    self.__target(_self.__args, *_self.__kwargs)
  File "/home/gioppo/git/cloudopting-crane/commander/toolbox/docker.py", line 99, in buildThread
    fileUtils.createFile(os.path.join(cwd, settings.FS_DEF_DOCKER_BUILD_PID), str(p.pid))
NameError: global name 'fileUtils' is not defined

127.0.0.1 - - [10/Jul/2015 16:17:49] "GET /builder/images/CTdV02EQ-IMcsi_clearoapachedc HTTP/1.1" 200 -

**Comment by gioppoluca** [comment]
I have added some logging in the java part and managed exception in the check since it does not get the image due to an error and the http returned a 400 and the DockerException was raised and this caused the process to start again
Now the process stop.
But we have errors in the docker biuld
Have you pushed the crane mods you did yesterday?

**Comment by j-fuentes** [comment]
I have pushed just now.

**Comment by j-fuentes** [comment]
Now I get the three docker images for the clearo application, but not the docker-compose.yml.

But let me check one more thing because the datastore is still beign erased (there must be another error in another operation).

**Comment by j-fuentes** [comment]
Datastore is now fixed. It will no self-erase anymore. https://github.com/CloudOpting/cloudopting-crane/commit/da127e781669d2d7d04e4c7b27a8e2a8a28b1380

I tried to run the Clearo example one more time. `puppet apply` returns not zero. Here is the log https://gist.github.com/j-fuentes/1df67d1cf675602dbc0e.

**Comment by gioppoluca** [comment]
## I know the problem does not find tomcat

Inviato da Libero Mail per Android Giovedì, 16 Luglio 2015, 11:57AM +02:00 da Jose Fuentes Castillo < notifications@github.com> :
