### ISSUE TITLE
co_commander not starting

### ISSUE THREAD

**Issue by gioppoluca** [CloudOpting/cloudopting-crane#6]
Seems it does not find "coengine".
Followed the instructions in the readme.

co_emulatedhost | ln: failed to create symbolic link '/sys/fs/cgroup/systemd/name=systemd': Operation not permitted
co_engine       | ln: failed to create symbolic link '/sys/fs/cgroup/systemd/name=systemd': Operation not permitted
co_engine       | time="2015-12-14T15:42:09.551794978Z" level=info msg="API listen on [::]:4243" 
co_engine       | time="2015-12-14T15:42:09.555648541Z" level=info msg="API listen on /var/run/docker.sock" 
co_engine       | time="2015-12-14T15:42:09.650962622Z" level=warning msg="Udev sync is not supported. This will lead to unexpected behavior, data loss and errors. For more information, see https://docs.docker.com/reference/commandline/daemon/#daemon-storage-driver-option" 
co_engine       | time="2015-12-14T15:42:09.656230610Z" level=error msg="There are no more loopback devices available." 
co_engine       | time="2015-12-14T15:42:09.656345150Z" level=fatal msg="Error starting daemon: error initializing graphdriver: loopback mounting failed" 
co_engine exited with code 1
co_emulatedhost | time="2015-12-14T15:42:10.618897768Z" level=info msg="API listen on /var/run/docker.sock" 
co_emulatedhost | time="2015-12-14T15:42:10.636538839Z" level=info msg="API listen on [::]:4243" 
co_emulatedhost | time="2015-12-14T15:42:10.734487892Z" level=warning msg="Udev sync is not supported. This will lead to unexpected behavior, data loss and errors. For more information, see https://docs.docker.com/reference/commandline/daemon/#daemon-storage-driver-option" 
co_emulatedhost | time="2015-12-14T15:42:10.736020489Z" level=error msg="There are no more loopback devices available." 
co_emulatedhost | time="2015-12-14T15:42:10.736138102Z" level=fatal msg="Error starting daemon: error initializing graphdriver: loopback mounting failed" 
co_emulatedhost exited with code 0
co_commander    | Traceback (most recent call last):
co_commander    |   File "/usr/src/commander/commander.py", line 9, in <module>
co_commander    |     from controllers.builder import builderOps
co_commander    |   File "/usr/src/commander/controllers/builder/builderOps.py", line 9, in <module>
co_commander    |     from toolbox import docker
co_commander    |   File "/usr/src/commander/toolbox/docker.py", line 73, in <module>
co_commander    |     defaultDockerClient = dockerClient()
co_commander    |   File "/usr/src/commander/toolbox/docker.py", line 69, in dockerClient
co_commander    |     raise Exception("Cannot connect with docker client at \'"+base_url+"\'")
co_commander    | Exception: Cannot connect with docker client at 'https://coengine:4243'
co_commander exited with code 1

**Comment by j-fuentes** [comment]
Trying to replicate the error.

Which docker-compose file are you using? `pilot-dev.yml`, `production.yml`, `development.yml`...

**Comment by j-fuentes** [comment]
The problem is because it is prepared to work with `aufs` and Centos do not support it.

I've changed the storage driver to `devicemapper` (branch `devicemapper`). It still works on my ubuntu and should work on CentOS natively.

**Comment by gioppoluca** [comment]
not yet:
Creating co_engine
Recreating co_commander
Attaching to co_redis, co_registry, co_emulatedhost, co_engine, co_commander
co_registry     | time="2015-12-15T10:16:58Z" level=warning msg="No HTTP secret provided - generated random secret. This may cause problems with uploads if multiple registries are behind a load-balancer. To provide a shared secret, fill in http.secret in the configuration file or set the REGISTRY_HTTP_SECRET environment variable." go.version=go1.5.2 instance.id=23c5d670-3063-489b-86c2-ee74bbcc0185 version=v2.2.1 
co_redis        | 1:C 15 Dec 10:16:56.302 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
co_redis        |                 _._  
co_redis        |            _.-``__ ''-._  
co_redis        |       _.-``    `.`_.  ''-._           Redis 3.0.5 (00000000/0) 64 bit
co_emulatedhost | ln: failed to create symbolic link '/sys/fs/cgroup/systemd/name=systemd': Operation not permitted
co_engine       | ln: failed to create symbolic link '/sys/fs/cgroup/systemd/name=systemd': Operation not permitted
co_registry     | time="2015-12-15T10:16:58Z" level=info msg="redis not configured" go.version=go1.5.2 instance.id=23c5d670-3063-489b-86c2-ee74bbcc0185 version=v2.2.1 
co_registry     | time="2015-12-15T10:16:58Z" level=info msg="using inmemory blob descriptor cache" go.version=go1.5.2 instance.id=23c5d670-3063-489b-86c2-ee74bbcc0185 version=v2.2.1 
co_redis        |   .-`.-``.``\/    _.,_ ''-._                                   
co_redis        |  (    '      ,       .-`  | `,    )     Running in standalone mode
co_redis        |  |`-._`-...-` __...-.`-._|'`_.-'|     Port: 6379
co_redis        |  |`-._   `._    /     _.-'    |     PID: 1
co_redis        |`-._    `-._`-./  _.-'    _.-'  
co_redis        |  |`-._`-._`-.**.-'    _.-'_.-'|  
co_engine       | time="2015-12-15T10:17:07.678803372Z" level=info msg="API listen on /var/run/docker.sock" 
co_redis        |  |    `-._`-._        _.-'_.-'    |           http://redis.io  
co_redis        |   `-._`-._`-.**.-'_.-'    _.-'  
co_redis        |  |`-._`-._`-.**.-'    _.-'_.-'|  
co_redis        |  |    `-._`-._        _.-'_.-'    |  
co_redis        |   `-._`-._`-.**.-'_.-'    _.-'  
co_redis        |       `-._    `-.__.-'    _.-'                                       
co_redis        |`-._        _.-'  
co_redis        |               `-.__.-'  
co_redis        | 
co_emulatedhost | time="2015-12-15T10:17:04.739443324Z" level=warning msg="Udev sync is not supported. This will lead to unexpected behavior, data loss and errors. For more information, see https://docs.docker.com/reference/commandline/daemon/#daemon-storage-driver-option" 
co_registry     | time="2015-12-15T10:16:58Z" level=info msg="Starting upload purge in 7m0s" go.version=go1.5.2 instance.id=23c5d670-3063-489b-86c2-ee74bbcc0185 version=v2.2.1 
co_engine       | time="2015-12-15T10:17:07.878377910Z" level=info msg="API listen on [::]:4243" 
co_redis        | 1:M 15 Dec 10:16:56.311 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
co_emulatedhost | time="2015-12-15T10:17:04.751117154Z" level=error msg="There are no more loopback devices available." 
co_emulatedhost | time="2015-12-15T10:17:04.751272481Z" level=fatal msg="Error starting daemon: error initializing graphdriver: loopback mounting failed" 
co_registry     | time="2015-12-15T10:16:58Z" level=info msg="listening on [::]:5000, tls" go.version=go1.5.2 instance.id=23c5d670-3063-489b-86c2-ee74bbcc0185 version=v2.2.1 
co_engine       | time="2015-12-15T10:17:08.479123288Z" level=warning msg="Udev sync is not supported. This will lead to unexpected behavior, data loss and errors. For more information, see https://docs.docker.com/reference/commandline/daemon/#daemon-storage-driver-option" 
co_redis        | 1:M 15 Dec 10:16:56.311 # Server started, Redis version 3.0.5
co_redis        | 1:M 15 Dec 10:16:56.311 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
co_redis        | 1:M 15 Dec 10:16:56.311 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
co_redis        | 1:M 15 Dec 10:16:56.312 \* DB loaded from disk: 0.000 seconds
co_redis        | 1:M 15 Dec 10:16:56.312 \* The server is now ready to accept connections on port 6379
co_engine       | time="2015-12-15T10:17:08.509915192Z" level=error msg="There are no more loopback devices available." 
co_engine       | time="2015-12-15T10:17:08.515422317Z" level=fatal msg="Error starting daemon: error initializing graphdriver: loopback mounting failed" 
co_engine exited with code 1
co_commander    | Traceback (most recent call last):
co_commander    |   File "/usr/src/commander/commander.py", line 9, in <module>
co_commander    |     from controllers.builder import builderOps
co_commander    |   File "/usr/src/commander/controllers/builder/builderOps.py", line 9, in <module>
co_commander    |     from toolbox import docker
co_commander    |   File "/usr/src/commander/toolbox/docker.py", line 73, in <module>
co_commander    |     defaultDockerClient = dockerClient()
co_commander    |   File "/usr/src/commander/toolbox/docker.py", line 69, in dockerClient
co_commander    |     raise Exception("Cannot connect with docker client at \'"+base_url+"\'")
co_commander    | Exception: Cannot connect with docker client at 'https://coengine:4243'
co_commander exited with code 1

**Comment by gioppoluca** [comment]
This could help
https://github.com/jpetazzo/dind/issues/19

**Comment by gioppoluca** [comment]
btw using dind could not be the best option.
http://jpetazzo.github.io/2015/09/03/do-not-use-docker-in-docker-for-ci/

**Comment by j-fuentes** [comment]
Changed the storage driver to devicemapper. Tested on a CentOS and it worked.

Please, try it and give me feedback.

Thanks

**Comment by gioppoluca** [comment]
Still some problems:
[root@localhost cloudopting-crane]# docker-compose -f pilot-dev.yml  up
Starting co_redis
Creating co_registry
Creating co_emulatedhost
Creating co_engine
Recreating co_commander
Attaching to co_redis, co_registry, co_emulatedhost, co_engine, co_commander
co_redis        | 1:C 17 Dec 09:17:35.665 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
co_redis        |                 _._  
co_redis        |            _.-``__ ''-._  
co_redis        |       _.-``    `.`_.  ''-._           Redis 3.0.5 (00000000/0) 64 bit
co_redis        |   .-`.-``.``\/    _.,_ ''-._                                   
co_redis        |  (    '      ,       .-`  | `,    )     Running in standalone mode
co_redis        |  |`-._`-...-` __...-.`-._|'`_.-'|     Port: 6379
co_redis        |  |`-._   `._    /     _.-'    |     PID: 1
co_redis        |`-._    `-._`-./  _.-'    _.-'  
co_redis        |  |`-._`-._`-.**.-'    _.-'_.-'|  
co_redis        |  |    `-._`-._        _.-'_.-'    |           http://redis.io  
co_redis        |   `-._`-._`-.**.-'_.-'    _.-'  
co_redis        |  |`-._`-._`-.**.-'    _.-'_.-'|  
co_redis        |  |    `-._`-._        _.-'_.-'    |  
co_redis        |   `-._`-._`-.**.-'_.-'    _.-'  
co_redis        |       `-._    `-.__.-'    _.-'                                       
co_redis        |`-._        _.-'  
co_redis        |               `-.__.-'  
co_redis        | 
co_redis        | 1:M 17 Dec 09:17:35.681 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
co_redis        | 1:M 17 Dec 09:17:35.681 # Server started, Redis version 3.0.5
co_redis        | 1:M 17 Dec 09:17:35.682 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
co_redis        | 1:M 17 Dec 09:17:35.682 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
co_redis        | 1:M 17 Dec 09:17:35.696 \* DB loaded from disk: 0.014 seconds
co_redis        | 1:M 17 Dec 09:17:35.696 \* The server is now ready to accept connections on port 6379
co_registry     | time="2015-12-17T09:17:38Z" level=warning msg="No HTTP secret provided - generated random secret. This may cause problems with uploads if multiple registries are behind a load-balancer. To provide a shared secret, fill in http.secret in the configuration file or set the REGISTRY_HTTP_SECRET environment variable." go.version=go1.5.2 instance.id=4f99d5c7-b024-4575-b85c-7b5eb348f183 version=v2.2.1 
co_registry     | time="2015-12-17T09:17:38Z" level=info msg="redis not configured" go.version=go1.5.2 instance.id=4f99d5c7-b024-4575-b85c-7b5eb348f183 version=v2.2.1 
co_registry     | time="2015-12-17T09:17:38Z" level=info msg="using inmemory blob descriptor cache" go.version=go1.5.2 instance.id=4f99d5c7-b024-4575-b85c-7b5eb348f183 version=v2.2.1 
co_registry     | time="2015-12-17T09:17:38Z" level=info msg="Starting upload purge in 9m0s" go.version=go1.5.2 instance.id=4f99d5c7-b024-4575-b85c-7b5eb348f183 version=v2.2.1 
co_registry     | time="2015-12-17T09:17:38Z" level=info msg="listening on [::]:5000, tls" go.version=go1.5.2 instance.id=4f99d5c7-b024-4575-b85c-7b5eb348f183 version=v2.2.1 
co_emulatedhost | ln: failed to create symbolic link '/sys/fs/cgroup/systemd/name=systemd': Operation not permitted
co_emulatedhost | time="2015-12-17T09:17:43.905606343Z" level=fatal msg="Could not load X509 key pair (cert: \"/var/lib/coengine/certs/server-cert.pem\", key: \"/var/lib/coengine/certs/server-key.pem\"): open /var/lib/coengine/certs/server-cert.pem: no such file or directory" 
co_engine       | ln: failed to create symbolic link '/sys/fs/cgroup/systemd/name=systemd': Operation not permitted
co_engine       | time="2015-12-17T09:17:51.708596366Z" level=info msg="API listen on /var/run/docker.sock" 
co_engine       | time="2015-12-17T09:17:52.906727926Z" level=info msg="API listen on [::]:4243" 
co_engine       | time="2015-12-17T09:17:57.876324709Z" level=warning msg="Udev sync is not supported. This will lead to unexpected behavior, data loss and errors. For more information, see https://docs.docker.com/reference/commandline/daemon/#daemon-storage-driver-option" 
co_engine       | time="2015-12-17T09:17:57.887715542Z" level=error msg="There are no more loopback devices available." 
co_engine       | time="2015-12-17T09:17:57.888028151Z" level=fatal msg="Error starting daemon: error initializing graphdriver: loopback mounting failed" 
co_emulatedhost exited with code 0
co_engine exited with code 1
co_commander    | Traceback (most recent call last):
co_commander    |   File "/usr/src/commander/commander.py", line 9, in <module>
co_commander    |     from controllers.builder import builderOps
co_commander    |   File "/usr/src/commander/controllers/builder/builderOps.py", line 9, in <module>
co_commander    |     from toolbox import docker
co_commander    |   File "/usr/src/commander/toolbox/docker.py", line 73, in <module>
co_commander    |     defaultDockerClient = dockerClient()
co_commander    |   File "/usr/src/commander/toolbox/docker.py", line 69, in dockerClient
co_commander    |     raise Exception("Cannot connect with docker client at \'"+base_url+"\'")
co_commander    | Exception: Cannot connect with docker client at 'https://coengine:4243'
co_commander exited with code 1
Killing co_emulatedhost ... done
Killing co_registry ... done
Killing co_redis ... done

**Comment by gioppoluca** [comment]
Can you send me the steps to reset the environment so that is possible to start from a clean one?
Luca

**Comment by j-fuentes** [comment]
Remove all the containers:
`docker rm -v -f $(docker ps -a -q)`

**Comment by gioppoluca** [comment]
Seems to work
