### ISSUE TITLE
Save the puppet manifest with the original name

### ISSUE THREAD

**Issue by j-fuentes** [CloudOpting/cloudopting-crane#8]
Save the puppet manifest with the original name instead of rename it to `manifest.pp`

**Comment by gioppoluca** [comment]
in the root context
:D

**Comment by j-fuentes** [comment]
Done in https://github.com/CloudOpting/cloudopting-crane/releases/tag/1.0-beta

Commit: https://github.com/CloudOpting/cloudopting-crane/commit/9bc116db6424ce5e53df29a09d3dc0f2ce6895bc
